import { useMemo, useState, type ReactElement } from 'react'
import type { IdeaStatus, Task, TaskInput, TaskType, TaskTypeInput, VideoIdea } from '@shared/types'
import { useIdeasData } from '../../hooks/useIdeasData'
import { formatDate } from '../../lib/format'
import { taskColor } from '../../lib/taskTypeColors'
import { isTaskOverdue, sortTasksByUrgency } from '../../lib/taskUrgency'
import { TaskFormModal } from './TaskFormModal'

type SubTab = 'liste' | 'proprietes'

interface TaskRowProps {
  task: Task
  taskTypesById: Map<number, TaskType>
  ideasById: Map<number, VideoIdea>
  statusColors: Record<IdeaStatus, string>
  selected: boolean
  onToggleSelect: () => void
  onEdit: () => void
  onReschedule: (date: string, time: string) => void
  onCancel: () => void
}

function TaskRow({
  task,
  taskTypesById,
  ideasById,
  statusColors,
  selected,
  onToggleSelect,
  onEdit,
  onReschedule,
  onCancel
}: TaskRowProps): ReactElement {
  const overdue = isTaskOverdue(task)
  const [rescheduling, setRescheduling] = useState(false)
  const [draftDate, setDraftDate] = useState(task.dueDate ?? '')
  const [draftTime, setDraftTime] = useState(task.dueTime ?? '')
  const [confirmingCancel, setConfirmingCancel] = useState(false)

  const types = task.typeIds.map((id) => taskTypesById.get(id)).filter((t): t is TaskType => !!t)
  const linkedIdeas = task.ideaIds.map((id) => ideasById.get(id)).filter((i): i is VideoIdea => !!i)
  const isClosed = task.status !== 'pending'
  const color = taskColor(task, taskTypesById, statusColors)

  return (
    <div
      style={
        overdue
          ? { borderColor: '#ef444466', backgroundColor: '#ef44440f' }
          : { borderColor: `${color}40`, backgroundColor: `${color}14` }
      }
      className={`rounded-lg border px-4 py-3 ${isClosed ? 'opacity-60' : ''}`}
    >
      <div className="flex items-start gap-3">
        <input
          type="checkbox"
          checked={selected}
          onChange={onToggleSelect}
          className="mt-1 h-4 w-4 shrink-0 rounded border-white/20 bg-white/5 accent-blue-600"
        />
        <button type="button" onClick={onEdit} className="min-w-0 flex-1 text-left">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-lg">{task.emoji || '✅'}</span>
            <span
              className={`font-medium ${isClosed ? 'text-gray-500 line-through' : 'text-gray-100'}`}
            >
              {task.title}
            </span>
            {task.autoGenerated && (
              <span className="rounded-full border border-white/10 bg-white/5 px-2 py-0.5 text-xs text-gray-500">
                Auto
              </span>
            )}
            {task.status === 'canceled' && (
              <span className="rounded-full border border-white/10 bg-white/5 px-2 py-0.5 text-xs text-gray-500">
                Annulée
              </span>
            )}
          </div>
          <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-gray-500">
            {task.dueDate && (
              <span className={overdue ? 'font-medium text-red-300' : ''}>
                📅 {formatDate(task.dueDate)}
                {task.dueTime ? ` à ${task.dueTime}` : ''}
              </span>
            )}
            {types.map((t) => (
              <span key={t.id}>
                {t.emoji} {t.name}
              </span>
            ))}
            {linkedIdeas.map((idea) => (
              <span key={idea.id}>🎥 {idea.title}</span>
            ))}
          </div>
        </button>
      </div>

      {overdue && !rescheduling && (
        <div className="mt-2 flex flex-wrap items-center gap-2 pl-7 text-xs">
          <span className="text-red-300">En retard —</span>
          <button
            type="button"
            onClick={() => setRescheduling(true)}
            className="rounded-md border border-white/10 px-2 py-1 text-gray-300 hover:bg-white/5"
          >
            Reporter
          </button>
          {confirmingCancel ? (
            <span className="flex items-center gap-2">
              <span className="text-gray-400">Confirmer l’annulation ?</span>
              <button
                type="button"
                onClick={onCancel}
                className="rounded bg-red-600 px-2 py-1 font-medium text-white hover:bg-red-500"
              >
                Oui
              </button>
              <button
                type="button"
                onClick={() => setConfirmingCancel(false)}
                className="text-gray-400 hover:text-gray-200"
              >
                Non
              </button>
            </span>
          ) : (
            <button
              type="button"
              onClick={() => setConfirmingCancel(true)}
              className="rounded-md border border-white/10 px-2 py-1 text-gray-300 hover:bg-white/5"
            >
              Annuler la tâche
            </button>
          )}
        </div>
      )}

      {overdue && rescheduling && (
        <div className="mt-2 flex flex-wrap items-center gap-2 pl-7 text-xs">
          <input
            type="date"
            value={draftDate}
            onChange={(e) => setDraftDate(e.target.value)}
            className="rounded-md border border-white/10 bg-white/5 px-2 py-1 text-gray-100 outline-none [color-scheme:dark]"
          />
          <input
            type="time"
            value={draftTime}
            onChange={(e) => setDraftTime(e.target.value)}
            className="rounded-md border border-white/10 bg-white/5 px-2 py-1 text-gray-100 outline-none [color-scheme:dark]"
          />
          <button
            type="button"
            onClick={() => {
              onReschedule(draftDate, draftTime)
              setRescheduling(false)
            }}
            className="rounded-md bg-blue-600 px-2 py-1 font-medium text-white hover:bg-blue-500"
          >
            Valider
          </button>
          <button
            type="button"
            onClick={() => setRescheduling(false)}
            className="text-gray-400 hover:text-gray-200"
          >
            Annuler
          </button>
        </div>
      )}
    </div>
  )
}

function TaskTypeRow({ type, onRemove }: { type: TaskType; onRemove: () => void }): ReactElement {
  const [confirming, setConfirming] = useState(false)
  return (
    <div className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[0.03] px-4 py-2.5">
      <span className="flex items-center gap-2 text-sm text-gray-200">
        <span className="text-lg">{type.emoji}</span>
        {type.name}
      </span>
      {confirming ? (
        <span className="flex items-center gap-2 text-xs">
          <span className="text-red-300">Supprimer ce type ?</span>
          <button
            onClick={onRemove}
            className="rounded bg-red-600 px-2 py-1 font-medium text-white hover:bg-red-500"
          >
            Confirmer
          </button>
          <button
            onClick={() => setConfirming(false)}
            className="text-gray-400 hover:text-gray-200"
          >
            Annuler
          </button>
        </span>
      ) : (
        <button
          onClick={() => setConfirming(true)}
          className="rounded-md px-2 py-1 text-xs text-red-400 hover:bg-red-500/10"
        >
          Supprimer
        </button>
      )}
    </div>
  )
}

function TaskTypesPanel({
  taskTypes,
  onCreate,
  onRemove
}: {
  taskTypes: TaskType[]
  onCreate: (input: TaskTypeInput) => Promise<void>
  onRemove: (id: number) => Promise<void>
}): ReactElement {
  const [name, setName] = useState('')
  const [emoji, setEmoji] = useState('📌')

  async function handleCreate(): Promise<void> {
    const trimmed = name.trim()
    if (!trimmed) return
    await onCreate({ name: trimmed, emoji: emoji.trim() || '📌' })
    setName('')
    setEmoji('📌')
  }

  return (
    <div className="max-w-xl space-y-4">
      <div className="rounded-lg border border-white/10 bg-white/[0.03] p-4">
        <h3 className="mb-2 text-sm font-medium text-gray-300">Nouveau type de tâche</h3>
        <div className="flex gap-2">
          <input
            value={emoji}
            onChange={(e) => setEmoji(e.target.value)}
            className="w-14 shrink-0 rounded-md border border-white/10 bg-white/5 px-2 py-2 text-center text-lg outline-none focus:border-blue-500/60"
          />
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleCreate()}
            placeholder="Nom du type (ex: Miniature)"
            className="flex-1 rounded-md border border-white/10 bg-white/5 px-3 py-2 text-sm text-gray-100 outline-none focus:border-blue-500/60"
          />
          <button
            onClick={handleCreate}
            className="rounded-md bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-500"
          >
            Ajouter
          </button>
        </div>
      </div>

      <div className="space-y-2">
        {taskTypes.map((type) => (
          <TaskTypeRow key={type.id} type={type} onRemove={() => onRemove(type.id)} />
        ))}
        {taskTypes.length === 0 && (
          <p className="text-sm text-gray-500">Aucun type de tâche créé pour l’instant.</p>
        )}
      </div>
    </div>
  )
}

export function TasksTab(): ReactElement {
  const { ideas, ideasById, taskTypes, taskTypesById, tasks, settings, loading, refresh } =
    useIdeasData()
  const [subTab, setSubTab] = useState<SubTab>('liste')
  const [creating, setCreating] = useState(false)
  const [editingTask, setEditingTask] = useState<Task | null>(null)
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set())
  const [confirmingBulkDelete, setConfirmingBulkDelete] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [typeFilterIds, setTypeFilterIds] = useState<number[]>([])

  const filteredTasks = useMemo(() => {
    const kw = keyword.trim().toLowerCase()
    return tasks.filter((task) => {
      if (typeFilterIds.length > 0 && !task.typeIds.some((id) => typeFilterIds.includes(id))) {
        return false
      }
      if (kw && !task.title.toLowerCase().includes(kw)) return false
      return true
    })
  }, [tasks, keyword, typeFilterIds])

  const pendingTasks = useMemo(
    () =>
      sortTasksByUrgency(
        filteredTasks.filter((t) => t.status === 'pending'),
        taskTypesById,
        ideasById
      ),
    [filteredTasks, taskTypesById, ideasById]
  )
  const closedTasks = useMemo(
    () =>
      [...filteredTasks]
        .filter((t) => t.status !== 'pending')
        .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)),
    [filteredTasks]
  )

  function toggleSelect(id: number): void {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  function toggleTypeFilter(id: number): void {
    setTypeFilterIds((prev) => (prev.includes(id) ? prev.filter((t) => t !== id) : [...prev, id]))
  }

  async function handleCreate(input: TaskInput): Promise<void> {
    await window.api.tasks.create(input)
    setCreating(false)
    await refresh()
  }

  async function handleUpdate(input: TaskInput): Promise<void> {
    if (!editingTask) return
    await window.api.tasks.update(editingTask.id, input)
    setEditingTask(null)
    await refresh()
  }

  async function handleDelete(): Promise<void> {
    if (!editingTask) return
    await window.api.tasks.remove(editingTask.id)
    setEditingTask(null)
    await refresh()
  }

  async function handleBulkDelete(): Promise<void> {
    await window.api.tasks.removeMany([...selectedIds])
    setSelectedIds(new Set())
    setConfirmingBulkDelete(false)
    await refresh()
  }

  async function handleReschedule(taskId: number, date: string, time: string): Promise<void> {
    await window.api.tasks.reschedule(taskId, date || null, time || null)
    await refresh()
  }

  async function handleCancelTask(taskId: number): Promise<void> {
    await window.api.tasks.setStatus(taskId, 'canceled')
    await refresh()
  }

  async function handleCreateType(input: TaskTypeInput): Promise<void> {
    await window.api.taskTypes.create(input)
    await refresh()
  }

  async function handleRemoveType(id: number): Promise<void> {
    await window.api.taskTypes.remove(id)
    await refresh()
  }

  return (
    <div className="flex h-full flex-col">
      <div className="flex items-center justify-between px-6 py-4">
        <div className="flex items-center gap-4">
          <h1 className="text-lg font-semibold text-gray-100">Tâches</h1>
          <div className="flex gap-1 rounded-lg border border-white/10 bg-white/[0.03] p-1">
            <button
              onClick={() => setSubTab('liste')}
              className={`rounded-md px-3 py-1 text-sm transition-colors ${
                subTab === 'liste' ? 'bg-blue-600 text-white' : 'text-gray-400 hover:text-gray-200'
              }`}
            >
              Liste
            </button>
            <button
              onClick={() => setSubTab('proprietes')}
              className={`rounded-md px-3 py-1 text-sm transition-colors ${
                subTab === 'proprietes'
                  ? 'bg-blue-600 text-white'
                  : 'text-gray-400 hover:text-gray-200'
              }`}
            >
              Propriétés
            </button>
          </div>
        </div>
        {subTab === 'liste' && (
          <div className="flex items-center gap-3">
            {selectedIds.size > 0 &&
              (confirmingBulkDelete ? (
                <span className="flex items-center gap-2 text-xs">
                  <span className="text-red-300">Supprimer {selectedIds.size} tâche(s) ?</span>
                  <button
                    onClick={handleBulkDelete}
                    className="rounded bg-red-600 px-2 py-1 font-medium text-white hover:bg-red-500"
                  >
                    Confirmer
                  </button>
                  <button
                    onClick={() => setConfirmingBulkDelete(false)}
                    className="text-gray-400 hover:text-gray-200"
                  >
                    Annuler
                  </button>
                </span>
              ) : (
                <button
                  onClick={() => setConfirmingBulkDelete(true)}
                  className="rounded-md border border-red-500/40 px-3 py-1.5 text-sm text-red-300 hover:bg-red-500/10"
                >
                  Supprimer la sélection ({selectedIds.size})
                </button>
              ))}
            <button
              onClick={() => setCreating(true)}
              className="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-500"
            >
              + Nouvelle tâche
            </button>
          </div>
        )}
      </div>

      <div className="flex-1 space-y-6 overflow-y-auto px-6 pb-6">
        {loading ? (
          <p className="text-sm text-gray-500">Chargement...</p>
        ) : subTab === 'proprietes' ? (
          <TaskTypesPanel
            taskTypes={taskTypes}
            onCreate={handleCreateType}
            onRemove={handleRemoveType}
          />
        ) : (
          <>
            <div className="flex flex-wrap items-center gap-2 rounded-lg border border-white/10 bg-white/[0.03] p-3">
              <input
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
                placeholder="Rechercher une tâche..."
                className="min-w-[200px] flex-1 rounded-md border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-gray-100 outline-none focus:border-blue-500/60"
              />
              <div className="flex flex-wrap gap-1.5">
                {taskTypes.map((type) => (
                  <button
                    key={type.id}
                    type="button"
                    onClick={() => toggleTypeFilter(type.id)}
                    className={`rounded-md border px-2 py-1 text-xs transition-colors ${
                      typeFilterIds.includes(type.id)
                        ? 'border-blue-500/60 bg-blue-500/20 text-blue-200'
                        : 'border-white/10 bg-white/5 text-gray-400 hover:bg-white/10'
                    }`}
                  >
                    {type.emoji} {type.name}
                  </button>
                ))}
              </div>
              {(keyword || typeFilterIds.length > 0) && (
                <button
                  type="button"
                  onClick={() => {
                    setKeyword('')
                    setTypeFilterIds([])
                  }}
                  className="text-sm text-gray-500 hover:text-gray-300"
                >
                  Réinitialiser
                </button>
              )}
            </div>

            <section>
              <h2 className="mb-2 text-sm font-medium text-gray-300">
                En attente ({pendingTasks.length})
              </h2>
              {pendingTasks.length === 0 ? (
                <p className="text-sm text-gray-500">Aucune tâche en attente.</p>
              ) : (
                <div className="space-y-2">
                  {pendingTasks.map((task) => (
                    <TaskRow
                      key={task.id}
                      task={task}
                      taskTypesById={taskTypesById}
                      ideasById={ideasById}
                      statusColors={settings.statusColors}
                      selected={selectedIds.has(task.id)}
                      onToggleSelect={() => toggleSelect(task.id)}
                      onEdit={() => setEditingTask(task)}
                      onReschedule={(date, time) => handleReschedule(task.id, date, time)}
                      onCancel={() => handleCancelTask(task.id)}
                    />
                  ))}
                </div>
              )}
            </section>

            {closedTasks.length > 0 && (
              <section>
                <h2 className="mb-2 text-sm font-medium text-gray-500">
                  Terminées / annulées ({closedTasks.length})
                </h2>
                <div className="space-y-2">
                  {closedTasks.map((task) => (
                    <TaskRow
                      key={task.id}
                      task={task}
                      taskTypesById={taskTypesById}
                      ideasById={ideasById}
                      statusColors={settings.statusColors}
                      selected={selectedIds.has(task.id)}
                      onToggleSelect={() => toggleSelect(task.id)}
                      onEdit={() => setEditingTask(task)}
                      onReschedule={(date, time) => handleReschedule(task.id, date, time)}
                      onCancel={() => handleCancelTask(task.id)}
                    />
                  ))}
                </div>
              </section>
            )}
          </>
        )}
      </div>

      {creating && (
        <TaskFormModal
          task={null}
          taskTypes={taskTypes}
          ideas={ideas}
          onClose={() => setCreating(false)}
          onSave={handleCreate}
          onTaskTypesChanged={refresh}
        />
      )}

      {editingTask && (
        <TaskFormModal
          task={editingTask}
          taskTypes={taskTypes}
          ideas={ideas}
          onClose={() => setEditingTask(null)}
          onSave={handleUpdate}
          onDelete={handleDelete}
          onTaskTypesChanged={refresh}
        />
      )}
    </div>
  )
}
