import { getDb } from './index'
import { listIdeas } from './ideas'
import { listObjects } from './objects'
import type { OwnedObject, Task, TaskInput, TaskStatus, VideoIdea } from '../../shared/types'

interface TaskRow {
  id: number
  title: string
  emoji: string | null
  due_date: string | null
  due_time: string | null
  status: TaskStatus
  auto_generated: number
  auto_key: string | null
  created_at: string
  updated_at: string
}

function getTypeIds(taskId: number): number[] {
  const rows = getDb()
    .prepare('SELECT task_type_id FROM task_type_links WHERE task_id = ?')
    .all(taskId) as { task_type_id: number }[]
  return rows.map((r) => r.task_type_id)
}

function getIdeaIds(taskId: number): number[] {
  const rows = getDb().prepare('SELECT idea_id FROM task_ideas WHERE task_id = ?').all(taskId) as {
    idea_id: number
  }[]
  return rows.map((r) => r.idea_id)
}

function toTask(row: TaskRow): Task {
  return {
    id: row.id,
    title: row.title,
    emoji: row.emoji,
    dueDate: row.due_date,
    dueTime: row.due_time,
    status: row.status,
    autoGenerated: row.auto_generated === 1,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    typeIds: getTypeIds(row.id),
    ideaIds: getIdeaIds(row.id)
  }
}

function setTaskTypes(taskId: number, typeIds: number[]): void {
  const db = getDb()
  db.prepare('DELETE FROM task_type_links WHERE task_id = ?').run(taskId)
  const insert = db.prepare('INSERT INTO task_type_links (task_id, task_type_id) VALUES (?, ?)')
  for (const typeId of typeIds) insert.run(taskId, typeId)
}

function setTaskIdeas(taskId: number, ideaIds: number[]): void {
  const db = getDb()
  db.prepare('DELETE FROM task_ideas WHERE task_id = ?').run(taskId)
  const insert = db.prepare('INSERT INTO task_ideas (task_id, idea_id) VALUES (?, ?)')
  for (const ideaId of ideaIds) insert.run(taskId, ideaId)
}

function getTaskById(id: number): Task {
  const row = getDb().prepare('SELECT * FROM tasks WHERE id = ?').get(id) as TaskRow
  return toTask(row)
}

export function listTasks(): Task[] {
  syncAutoTasks()
  const rows = getDb()
    .prepare('SELECT * FROM tasks ORDER BY due_date IS NULL, due_date ASC, id DESC')
    .all() as TaskRow[]
  return rows.map(toTask)
}

export function createTask(input: TaskInput): Task {
  const db = getDb()
  const result = db
    .prepare(
      `INSERT INTO tasks (title, emoji, due_date, due_time, status)
       VALUES (@title, @emoji, @dueDate, @dueTime, @status)`
    )
    .run({
      title: input.title,
      emoji: input.emoji,
      dueDate: input.dueDate,
      dueTime: input.dueTime,
      status: input.status
    })

  const taskId = result.lastInsertRowid as number
  setTaskTypes(taskId, input.typeIds)
  setTaskIdeas(taskId, input.ideaIds)
  return getTaskById(taskId)
}

export function updateTask(id: number, input: TaskInput): Task {
  const db = getDb()
  db.prepare(
    `UPDATE tasks SET
       title = @title,
       emoji = @emoji,
       due_date = @dueDate,
       due_time = @dueTime,
       status = @status,
       updated_at = datetime('now')
     WHERE id = @id`
  ).run({
    id,
    title: input.title,
    emoji: input.emoji,
    dueDate: input.dueDate,
    dueTime: input.dueTime,
    status: input.status
  })

  setTaskTypes(id, input.typeIds)
  setTaskIdeas(id, input.ideaIds)
  return getTaskById(id)
}

export function setTaskStatus(id: number, status: TaskStatus): Task {
  getDb()
    .prepare(`UPDATE tasks SET status = @status, updated_at = datetime('now') WHERE id = @id`)
    .run({ id, status })
  return getTaskById(id)
}

/** Reporting an overdue task to a new date/time always brings it back to "pending". */
export function rescheduleTask(id: number, dueDate: string | null, dueTime: string | null): Task {
  getDb()
    .prepare(
      `UPDATE tasks SET
         due_date = @dueDate,
         due_time = @dueTime,
         status = 'pending',
         updated_at = datetime('now')
       WHERE id = @id`
    )
    .run({ id, dueDate, dueTime })
  return getTaskById(id)
}

export function removeTask(id: number): void {
  getDb().prepare('DELETE FROM tasks WHERE id = ?').run(id)
}

export function removeTasks(ids: number[]): void {
  const db = getDb()
  const del = db.prepare('DELETE FROM tasks WHERE id = ?')
  const txn = db.transaction((taskIds: number[]) => {
    for (const taskId of taskIds) del.run(taskId)
  })
  txn(ids)
}

// ---------------------------------------------------------------------------
// Automation: tasks that create/resolve themselves based on the state of ideas and objects.
// Urgency/priority is never stored — it's computed on the fly in the renderer from each task's
// due date, its idea's remaining pipeline stages, and its type's position in that pipeline.
// ---------------------------------------------------------------------------

function daysUntil(dateStr: string): number {
  const target = new Date(dateStr.slice(0, 10)).getTime()
  const today = new Date(new Date().toISOString().slice(0, 10)).getTime()
  return Math.round((target - today) / 86_400_000)
}

interface DesiredAutoTask {
  autoKey: string
  title: string
  emoji: string
  dueDate: string | null
  dueTime: string | null
  typeName: string
  typeEmoji: string
  ideaId: number
}

function computeDesiredAutoTasks(ideas: VideoIdea[], objects: OwnedObject[]): DesiredAutoTask[] {
  const objectsById = new Map(objects.map((o) => [o.id, o]))
  const desired: DesiredAutoTask[] = []

  for (const idea of ideas) {
    // Rule 1 — an object needed for a shoot happening within 7 days hasn't been bought yet.
    if (idea.shootDate !== null) {
      const shootDays = daysUntil(idea.shootDate)
      if (shootDays >= 0 && shootDays <= 7) {
        for (const objectId of idea.objectIds) {
          const object = objectsById.get(objectId)
          if (!object || object.purchased) continue
          desired.push({
            autoKey: `buy-object-${objectId}-${idea.id}`,
            title: `Acheter « ${object.name} » (pour « ${idea.title} »)`,
            emoji: '🛒',
            dueDate: idea.shootDate,
            dueTime: null,
            typeName: 'Achat',
            typeEmoji: '🛒',
            ideaId: idea.id
          })
        }
      }

      // Rule 2 — a shoot is coming up within 3 days and the idea hasn't moved past prep yet.
      if (
        shootDays >= 0 &&
        shootDays <= 3 &&
        (idea.status === 'idea' || idea.status === 'preparation')
      ) {
        desired.push({
          autoKey: `shoot-soon-${idea.id}`,
          title: `Tournage imminent : « ${idea.title} »`,
          emoji: '🎬',
          dueDate: idea.shootDate,
          dueTime: null,
          typeName: 'Tournage',
          typeEmoji: '🎬',
          ideaId: idea.id
        })
      }
    }

    // Rule 3 — a video is scheduled and its publish date is within 2 days.
    if (idea.status === 'scheduled' && idea.publishDate !== null) {
      const publishDays = daysUntil(idea.publishDate)
      if (publishDays >= 0 && publishDays <= 2) {
        desired.push({
          autoKey: `publish-soon-${idea.id}`,
          title: `Publication imminente : « ${idea.title} »`,
          emoji: '📤',
          dueDate: idea.publishDate,
          dueTime: null,
          typeName: 'Publication',
          typeEmoji: '📤',
          ideaId: idea.id
        })
      }
    }
  }

  return desired
}

function getOrCreateTaskTypeId(name: string, emoji: string): number {
  const db = getDb()
  const existing = db.prepare('SELECT id FROM task_types WHERE name = ?').get(name) as
    { id: number } | undefined
  if (existing) return existing.id
  const result = db.prepare('INSERT INTO task_types (name, emoji) VALUES (?, ?)').run(name, emoji)
  return result.lastInsertRowid as number
}

/**
 * Keeps automation-created tasks in sync with reality: creates one for every condition that
 * currently applies (skipping ones that already exist and are still pending), and marks any
 * previously-created pending automation task "done" once its triggering condition is no longer
 * true (object bought, idea moved past prep, video published/rescheduled, etc). Runs on every
 * `listTasks()` call — cheap for this app's data volumes, and guarantees the list is always
 * accurate without needing a background scheduler.
 */
function syncAutoTasks(): void {
  const db = getDb()
  const ideas = listIdeas()
  const objects = listObjects()
  const desired = computeDesiredAutoTasks(ideas, objects)
  const desiredByKey = new Map(desired.map((d) => [d.autoKey, d]))

  const existingAuto = db
    .prepare("SELECT id, auto_key FROM tasks WHERE auto_generated = 1 AND status = 'pending'")
    .all() as { id: number; auto_key: string | null }[]
  const existingKeys = new Set(existingAuto.map((t) => t.auto_key))

  // Mark resolved: a pending automation task whose condition no longer applies.
  for (const existing of existingAuto) {
    if (existing.auto_key !== null && !desiredByKey.has(existing.auto_key)) {
      setTaskStatus(existing.id, 'done')
    }
  }

  // Create missing: a currently-true condition with no matching pending task yet.
  for (const item of desired) {
    if (existingKeys.has(item.autoKey)) continue

    const typeId = getOrCreateTaskTypeId(item.typeName, item.typeEmoji)
    const result = db
      .prepare(
        `INSERT INTO tasks (title, emoji, due_date, due_time, status, auto_generated, auto_key)
         VALUES (@title, @emoji, @dueDate, @dueTime, 'pending', 1, @autoKey)`
      )
      .run({
        title: item.title,
        emoji: item.emoji,
        dueDate: item.dueDate,
        dueTime: item.dueTime,
        autoKey: item.autoKey
      })
    const taskId = result.lastInsertRowid as number
    setTaskTypes(taskId, [typeId])
    setTaskIdeas(taskId, [item.ideaId])
  }
}
